/**
 * This file will be auto-generated by the Supabase CLI after running migrations.
 * Command: npx supabase gen types typescript --local > src/types/database.types.ts
 *
 * For now it exports a placeholder type to avoid TypeScript errors.
 */
export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
};
